apiVersion: v1

kind: Pod

metadata:
  name: envar-dev
  labels:
    purpose: for-developments

spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: course
          value: "KUBERNETES"
        - name: trainer
          value: "bharathkumar"